### ISSUE TITLE
 Question about predict_from_net.py

### ISSUE THREAD

**Issue by Paidalin** [justusschock/shapenet#12]
This is my parameter：
args = easydict.EasyDict({
    "visualize": True,
    "in_path": './inputs',
    "out_path": './outputs',
    "weight_file": './pretrained_face.ptj',
    "config_file": './example_configs/lfpw.config'
})

I encountered such a problem when I was running.
TypeError                                 Traceback (most recent call last)
<ipython-input-3-0aa16b0c8b73> in <module>
     92         print(_data.lmk)
     93         pred = process_sample(_data, img_size=config_dict["data"]["img_size"], net=net,
---> 94                               device=device)
     95 
     96         fname = os.path.split(_data.img_file)[-1].rsplit(".", 1)[0]

<ipython-input-3-0aa16b0c8b73> in process_sample(sample, img_size, net, device, crop)
     45 def process_sample(sample, img_size, net, device, crop=0.1):
     46     print(sample)
---> 47     lmk_bounds = sample.get_landmark_bounds(sample.lmk)
     48     min_y, min_x, max_y, max_x = lmk_bounds
     49     range_x = max_x - min_x

C:\ProgramData\Anaconda3\lib\site-packages\shapedata\base_data_processing.py in get_landmark_bounds(lmks)
    815         """
    816 
--> 817         min_y = lmks[:, 0].min()
    818         max_y = lmks[:, 0].max()
    819         min_x = lmks[:, 1].min()

TypeError: 'NoneType' object is not subscriptable

it seems that
_data = SingleShapeSingleImage2D.from_files(file)
did not read and process the data

I want to apply the existing model directly. Is there any problem with my parameter settings?

**Comment by justusschock** [comment]
This function assumes you are having landmarks. It seems, your landmarks are not loaded correctly. In which format did you store them?

**Comment by Paidalin** [comment]
> This function assumes you are having landmarks. It seems, your landmarks are not loaded correctly. In which format did you store them?

data = SingleShapeDataProcessing._get_files(
    os.path.abspath(args.in_path), extensions=[".png", ".jpg"])

 for idx, file in enumerate(tqdm(data)):
        _data = SingleShapeSingleImage2D.from_files(file)
        print(_data.lmk)

out:None


I did not modify the code of the file reading part, put the jpg picture in the inputs folder, after running _data.lmk is None, and after using _data.img input, the code can be run, but the effect is very poor.

**Comment by Paidalin** [comment]
args = easydict.EasyDict({
    "visualize": True,
    "in_path": './inputs/in',
    "out_path": './outputs',
    "weight_file": './pretrained_face.ptj',
    "config_file": './example_configs/lfpw.config'
})

this is my args

**Comment by justusschock** [comment]
Strange. This code works "as is" for me and others. What's your environment (I.e. Python Version os, did you install from source?)

**Comment by Paidalin** [comment]
I use pip install shapenet.
anaconda3 python3.7 windows10
I will debug again today.

**Comment by stonell007** [comment]
> I use pip install shapenet.
> anaconda3 python3.7 windows10
> I will debug again today.
亲，可以请教下嘛，我也在调这个代码，我qq:2502755152

**Comment by justusschock** [comment]
Sorry, I don't speak chinese
