### ISSUE TITLE
question: how to get values of training losses

### ISSUE THREAD

**Issue by mohaEs** [justusschock/shapenet#17]
Hi
I am not very familiar with delira pytorch. Could you kindly let us know, how we can plot or the get values of losses (train/val) of training procedure? is it in embedded in checkpoint_best.pth?
Thanks in advance.

**Comment by justusschock** [comment]
No it isn't. Actually they are logged via the internal logging module and you would have to setup a logging Handler (either visdom or tensorboard) to get them plotted. Setting up such a Logger is described in [this](https://github.com/justusschock/delira/blob/master/notebooks/tutorial_delira.ipynb) notebook

**Comment by justusschock** [comment]
I'll close this for now. If there are still some issues, feel free to reopen it
