### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by divastar** [justusschock/shapenet#19]
I got this error during installation

Collecting torch>=1.0.0; extra == "torch" (from delira[torch]<=0.3.1->shapenet==0.1.0)
  ERROR: Could not find a version that satisfies the requirement torch>=1.0.0; extra == "torch" (from delira[torch]<=0.3.1->shapenet==0.1.0) (from versions: 0.1
.2, 0.1.2.post1)
ERROR: No matching distribution found for torch>=1.0.0; extra == "torch" (from delira[torch]<=0.3.1->shapenet==0.1.0)

didn't find a solution yet 
can someone help?

**Comment by justusschock** [comment]
Are youn using widnows as OS?

**Comment by divastar** [comment]
yes

**Comment by justusschock** [comment]
The code has never been tested on windows. However it is most likely, that it works if you install pytorch via the instructions on the [official website](https://pytorch.org) before installing this repo.

**Comment by divastar** [comment]
apparently I installed pytorch with conda instead of pip.
:)
and it ok now:)
thanks
