### ISSUE TITLE
question  about predict

### ISSUE THREAD

**Issue by LilioISnotAfox** [justusschock/shapenet#20]
Hi:
  I use the default way to train the net .When I predict, I only replace the lmk_bounds with a face detector,but the landmarks not fit good.Is there anything I did wrong?
  And for last question about train,I find the shape data cannot set backend, so I set__BACKENDS = ['TORCH'] and it worked. Thanks for you help!

**Comment by LilioISnotAfox** [comment]
For the first question:I use the default additional transformations of lfpw.config. I have problem using the face detector with training,where should I add it?
For the second: I  install full version of delira cause the script (pip install delira[torch]  git clone https://github.com/justusschock/delira.git && cd delira && pip install .[torch])cannot work.But the result is good, I can use it anyway.

**Comment by justusschock** [comment]
You could write your own dataset and use this one for training. But the lfpw config should work, because these are the configs, I used to train the networks provided [here](https://drive.google.com/file/d/1QS2GUZK9xKWvpbDYgUCc-m0qI60TMnLj/view?usp=sharing). Can you try using these pretrained weights together with a face detector and see, whether this works?

**Comment by LilioISnotAfox** [comment]
When I predicted,I used the pretraind_face.ptj model,but the result was bad. How can I training data with face detector ?

**Comment by justusschock** [comment]
Well if that's the case, you made a mistake in dropping-in your face detector, because I have successfully used this exact model with this exact code and a face-detector. 

> How can I training data with face detector ?

I already told you:

> You could write your own dataset and use this one for training.

**Comment by LilioISnotAfox** [comment]
Thanks for help, I'll find where the bug is..
