### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by divastar** [justusschock/shapenet#21]
Hi . I run the code.
But there is a following error in shape_network.py:
def model(self, model: torch.nn.Module):
                         ^
SyntaxError: invalid syntax

**Comment by justusschock** [comment]
I just checked again and the given Code runs fine for me. Does it say, why the syntax is invalid?

**Comment by divastar** [comment]
Hi 
I guess this Syntax 
model: torch.nn.Module
(the ":")
thank you

**Comment by divastar** [comment]
File "C:\Users\korrine\AppData\Local\Continuum\anaconda3\envs\pytorch_new\lib\site-packages\shapenet\networks\single_shape\__init__.py", line 4, in <module>
    from .shape_network import ShapeNetwork as SingleShapeNetwork
  File "C:\Users\korrine\AppData\Local\Continuum\anaconda3\envs\pytorch_new\lib\site-packages\shapenet\networks\single_shape\shape_network.py", line 158
    def model(self, model: torch.nn.Module):
                                      ^
    SyntaxError: invalid syntax

**Comment by justusschock** [comment]
Are you using python 2.7? Because this syntax should be fine with 3.x

**Comment by divastar** [comment]
I am using python 3.7

**Comment by divastar** [comment]
Is it possible somehow to overcome this?
thank you

**Comment by justusschock** [comment]
This should usually work. I just set up a conda environment with python 3.7 on windows and everything works for me. 

To overcome this: This might be possible, but require some work. The value behind the ":" is only a type indication (also used for code completion), but it is not necessary for the code itself. Theoretically you should be able to delete these values (including the ":"). The disadvantage is, that you'd have to do it yourself and this kind of type-annotation is used quite often in this repo.

If you decide to do so, I'd be curious if this will fix your issue.

**Comment by divastar** [comment]
Are you using python 3.6?

**Comment by divastar** [comment]
You use 3.7 like me . saw it .

**Comment by justusschock** [comment]
I've already used it with python 3.5, 3.6 and 3.7 and never had these issues.

**Comment by divastar** [comment]
somehow it working after I exchanged scipy.misc import imsave with imageio in util.py

**Comment by justusschock** [comment]
Strange, but great that it works now. Maybe there was a hidden error in scipy, which propagated through all the code.
