### ISSUE TITLE
Cat-landmark detection

### ISSUE THREAD

**Issue by melgor** [justusschock/shapenet#22]
Hi,
I'm trying to use cat-landmark model. 
Here is my code:

```python
import numpy as np
import torch
from PIL import Image
import cv2

model = torch.jit.load("pretrained_cats.ptj")
model.eval()
model.cpu()

img = Image.open("dataset/poszukiwarka_kotow_splitted/train/Kot_62_Karinka/b.jpg").convert('L')
img_resized = img.resize((224,224))
img_preprocessed = np.array(img_resized).astype(np.float32)/255.
img_preprocessed = img_preprocessed[np.newaxis, np.newaxis, :, :]
print(np.max(img_preprocessed), np.min(img_preprocessed))

img_tensor = torch.from_numpy(img_preprocessed)
landmarks = model(img_tensor)
landmarks = landmarks.detach().numpy()[0]

img_resized_land = np.array(img_resized)
for x,y in landmarks:
    cv2.circle(img_resized_land, (x,y), 2,(255), -1)
```
input image:
![b](https://user-images.githubusercontent.com/2587438/58107594-76f76800-7bea-11e9-9867-c71fc09ba1e9.jpg)

output:
![download](https://user-images.githubusercontent.com/2587438/58107622-84aced80-7bea-11e9-84bd-3e3b24444661.png)

Result look like random one. What am I doing wrong?

**Comment by justusschock** [comment]
Your image does contain to much other stuff than the actual cat-face. Try cropping it to the face and resize afterwards

**Comment by melgor** [comment]
I cropped the image with tigher margin. The results are still the same:
![image](https://user-images.githubusercontent.com/2587438/58427844-12805100-80a1-11e9-9275-59325526c342.png)

**Comment by justusschock** [comment]
Ii just noticed, that the error is within your drawing function: the returned coordinates are `(y, x)` not `(x, y)`. I used the colimn-row notation throughout this implementation

**Comment by melgor** [comment]
Thanks, that helped:)
