### ISSUE TITLE
Embed in mobile as dlib

### ISSUE THREAD

**Issue by mediarl** [justusschock/shapenet#23]
Hi,

Is there a way to run this lib on mobile?
Dlib runs on Android and iOS but it's written in C++.
Any idea on how to run it on mobile devices?

Thanks

**Comment by justusschock** [comment]
Theoretically it is possible, but you'd have to (partially) rewrite it using [libtorch](https://pytorch.org/cppdocs/) as pytorchs c++ fronted (which can be compiled for Android). There shouldn't be any retraining necessary and you should be able to load the jotted weights in libtorch. Unfortunately I currently don't have the time to do this, but this shouldn't be that hard to do
