### ISSUE TITLE
Prediction time compared with dlib

### ISSUE THREAD

**Issue by An-Shank** [justusschock/shapenet#26]
Hi,

Previously, you had mentioned that your method is faster than dlib. However, when I downloaded the pretrained model and ran it on videos, I found that it was much slower than dlib. I used the same code (my own test app) and face detector (mobilenet SSD) to test shapenet and dlib.

**Comment by justusschock** [comment]
What is the time/frame you achieved for dlib and my model?

**Comment by An-Shank** [comment]
For dlib, it was 0.002 - 0.004 sec. For your model, it was 0.06 - 0.08 sec.

**Comment by justusschock** [comment]
Have you given it a bit of warmup? The problem ist, that when starting the model, a whole cuda context will be created, which is a relatively huge overhead, but must be done only once before the start. So this means, for a fair comparison you would not include this part in the benchmarking. Also you should set several benchmark flags in cudnn when benchmarking cuda code

**Comment by An-Shank** [comment]
I ran it on a CPU, not a GPU.

**Comment by justusschock** [comment]
Then this is the Problem! Dlibs code is optimized for CPU, mine is for GPU
