### ISSUE TITLE
error in script predict_from_net.py 

### ISSUE THREAD

**Issue by zyzray** [justusschock/shapenet#28]
In ./shapenet/scripts/predict_from_net.py line 118 
pred = net(img_tensor).cpu().numpy()["pred"][0]
should be
pred = net(img_tensor).cpu().numpy()[0]

obviously net(img_tensor).cpu().numpy() is not a dict

**Comment by justusschock** [comment]
Which delira version are you using? Because with the current version it should be a dict

**Comment by zyzray** [comment]
I'm using 0.4.1
After removing ["pred"] it works fine

**Comment by justusschock** [comment]
That's strange. It should be a dict. I don't know, when I have the time to look into this, but I'll try to do so asap

**Comment by justusschock** [comment]
That's strange. It should be a dict. I don't know, when I have the time to look into this, but I'll try to do so asap
