### ISSUE TITLE
Grayscale faces

### ISSUE THREAD

**Issue by joshbeal** [justusschock/shapenet#29]
I'm curious why the faces are converted to grayscale during training and prediction.

Is there a disadvantage to using faces in the three-channel RGB format?

**Comment by justusschock** [comment]
Not, it isn't. We rather found that the extra channels don't bring any benefits but only increase the first layer. 

Furthermore this was done to get a closer comparison to Active Appearance Models, which do the same (before feature extraction). 

This means: you can easily use 3 channels and should not expect worse results, but also not better ones.

**Comment by joshbeal** [comment]
Good to know! Thanks @justusschock
