### ISSUE TITLE
Is there a video Demo to show it's performance?

### ISSUE THREAD

**Issue by visonpon** [justusschock/shapenet#3]

**Comment by justusschock** [comment]
Not yet, but all results are given in the paper. I will have a look whether I can provide a video. In what kind of performance are you interested? Speed or accuracy? Because the first thing can't be shown by a video at all

**Comment by visonpon** [comment]
Accuracy, hope we can see the video performance soon, thanks~

**Comment by justusschock** [comment]
Do you have a good idea on how to provide the video? I don't want to add it to version control due to it's size.

**Comment by visonpon** [comment]
actually, i'm interest in your model's performance VS dlib or openpose.

**Comment by justusschock** [comment]
Yeah, but I don't know, how to provide it

**Comment by justusschock** [comment]
@visonpon on which data do you want me to show the performance? I could use some random images, but that would not cover the tracking capability...

**Comment by xjcvip007** [comment]
Thanks for your job~ One question, you mentioned that the method is a super real-time method in your paper, so why not test on a facial video?

**Comment by justusschock** [comment]
@xjcvip007 I'd like to do so, but I'm not aware of any publicly available dataset containing facial videos. Do you know one?

**Comment by xjcvip007** [comment]
@justusschock ,maybe 300vw datatset would meets your needs link: https://ibug.doc.ic.ac.uk/resources/300-VW/

**Comment by justusschock** [comment]
Update: I got it partially working on a video from 300-VW... The only problem is, that dlib seems to predict a line only. I currently don't know, what I'm doing wrong, but I'll keep trying...

**Comment by justusschock** [comment]
Demonstration Videos comparing our method to [`dlib`](https://dlib.net) can be found [here as overlay](https://drive.google.com/open?id=1hLaNuWy8eC3xs9qcTRzVZfBjdlB7xZ8c) and [here as side-by-side view](https://drive.google.com/file/d/128ZnFSOAhKnhN7xpgi6FR5KircnwIxca/view?usp=sharing)

Sorry, I can't embed them directly (they are too large). 

Evaluation Method: 

* initialization:
  * Detect Faces
  * Predict Shapes based on Initial Bounding Box
* tracking:
  * Predict Shapes based on Bounding Box extracted from `shapenet`'s prediction of the previous image 

My Conclusion: Both methods have similar accuracy, ours is a bit more robust (updating the bounding box from dlib's predictions led to a collapse), recovery from small errors is possible, huge different in speed (our method is far faster).
