### ISSUE TITLE
tf.train.Optimizer error

### ISSUE THREAD

**Issue by MiniMinyi** [justusschock/shapenet#30]
When I have tensorflow v2.0 in my environment and import shapenet, the `tf.train.Optimizer doesn't exist` error occurred.  Seems like it's a compatibility issue. I downgrade my tensorflow to version 1.14.0, I can still see this warning `The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.`

**Comment by justusschock** [comment]
This is a PyTorch framework. You should not need Tensorflow at all
