### ISSUE TITLE
Landmarks accuracy on lmk_bounds

### ISSUE THREAD

**Issue by jpmanoj** [justusschock/shapenet#5]
I have experimented with lmk_bounds in two scenarios :
1. Replaced lmk_bounds to the bounds of the face bounding box given by the face detector
2. Replaced lmk_bounds to the bounds of the image with only one face [Loosely cropped to the face - see the figure below]

![9011](https://user-images.githubusercontent.com/47267863/52997574-ec666780-3446-11e9-8611-ba7174836d6a.jpg)

In both the above mentioned scenarios the landmarks deviate from the ground truths drastically. Is this expected? Also can you please tell me your system configuration where you ran your code: I am able to achieve 3fps on my machine - GeForce GTX 960M 4GB with cuda-9

**Comment by justusschock** [comment]
It runs with 400 fps+ on a RTX 2080 Ti in half precision but you should be able to get significantly more fps even on your hardware. Did you try to predict or train?

I'm afraid you would have to retrain the network to your new bounds if replacing them. I had the same problem in the beginning when tracking sequences, but adding random offsets and scales to the landmarks during training und thus slightly modifying the crops did it. In this case. I might be able to retrain a network of dlbis face detector, but this should only take 3 hours.
