### ISSUE TITLE
could not compile: invalid syntax(predict_from_net.py, line 54)

### ISSUE THREAD

**Issue by soul-place** [justusschock/shapenet#7]

**Comment by justusschock** [comment]
Can you provide more context (`config_dict`, how did you install, python version etc.?)

**Comment by soul-place** [comment]
I installed shapenet from source code and my python version is  2.7.5. Running the script(python predict_from_net.py --visualize=true in_path=./test --weight_file=pretrained_face.ptj --config_file=../../example_configs/lfpw_config)
The error arises: File "predict_from_net.py", line 54 **config_dict["layer"]},  syntaxError: invalid syntax

**Comment by justusschock** [comment]
This is due to the python version. This repository supports only Python 3.6 and above. For backwards compatibility, you'd probably have to do only a few changes.
