### ISSUE TITLE
Does not the PCA operation leak landmarks to the training process?

### ISSUE THREAD

**Issue by creatist** [justusschock/shapenet#9]
Sorry, I have some doubts, how do you make the PCA process in predict stage? I read your code but still can not understand. And what is the target in training stage where you apply PCA with landmark points?

**Comment by justusschock** [comment]
The PCA is created on the landmarks from the training data only. The main components (sorted by decreasing variance) and the mean shape are used to build the shape layer. The network predicts weights for each of the components (weight for mean is fixed to 1), which are used to ensemble the final shape. This means, that similar to AAMs, you have a kind of encoding of your training data in your network, but it does not know your test data. 

I'm not sure, what you mean by "leak landmarks", but this method generalizes well on unseen test and validation data.

**Comment by justusschock** [comment]
Closing for now. Feel free to reopen, if the issue persists.
